# Generated by Django 4.1 on 2023-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_user_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="img",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
