# Generated by Django 4.1 on 2023-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcer", models.IntegerField(blank=True)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("details", models.CharField(blank=True, max_length=10000)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
