# Generated by Django 4.1 on 2023-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadArticle",
            fields=[
                ("obj_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
            ],
        ),
    ]
