# Generated by Django 4.1 on 2023-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_readarticle_read_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="added_on",
            field=models.DateTimeField(),
        ),
    ]
