# Generated by Django 4.1 on 2023-07-11 04:19

import app.myutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_announcement_added_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="reason",
            field=models.CharField(
                blank=True, default="User wasn't given immediate access", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unique_key",
            field=models.CharField(default=app.myutils.key_gen, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="suspended",
            field=models.BooleanField(default=True),
        ),
    ]
