# Generated by Django 4.1 on 2023-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_user_email_user_phone_number_user_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
